= Challenge 2

Your second challenge awaits! 

In this challenge, we want to see how comfortable you are explaining a technical topic.

Your audience is someone technical, but new to link:https://en.wikipedia.org/wiki/Version_control[version control^].

== Instructions

. Explain what a merge request/pull request is.
. Give examples on how to use it.

== Answer

//Assumption: Prior to rearding about pull requests, we assume the audience has a basic understanding of the version control concept (e.g. main & side branch usage).

== Pull requests / merge requests

=== Benefits
Pull requests (also known as merge requests, depending on the version control software you're using) are a key element for tracking code changes and cultivating cooperation within a development team.

=== How it works
* Let's say you've made a couple of changes to the code and you're now ready to submit your work to the main branch.
* By adding a pull request in the system, you invite other team members to review your code changes and send you feedback.
* Pull requests automatically show the differences between the already existing code and the one you've updated.
* Once you address the feedback, you're now ready to merge your code to the main branch.
