= Challenge 1

Your first challenge awaits! 

In this challenge, we want to get an idea of your writing style as it relates to software and computer technology.

== Instructions

. Choose any software or application that you use regularly.
. Write instructions on how to perform a common task related to the software or application.

.Example please?
****
Some ideas to get you started:

* Sending an attachment in link:https://signal.org/[Signal^].
* Forwarding an email with link:https://www.google.com/gmail/about/[Gmail^].
* Publishing a blog post with link:https://wordpress.com/[Wordpress^].
* Adding an extension to link:https://code.visualstudio.com/[Visual Studio Code^].
* Taking a screenshot with an link:https://www.apple.com/iphone/[iPhone^].
****

TIP: Keep the task concise. There's no need to over-complicate the instructions.

== Answer

== Changing the language on your Samsung Galaxy S10+ device

. Open the device.
. Navigate to *Settings > General Management > Language*.
. Select the *Add language* option.
. From the list of suggested languages, select the one of your preference.
. If you wish to make the new language the default one, tap *Set as default*. Alternatively, to keep the already existing language as default, tap *Keep current*.

NOTE: Depending on your software version, the instructions might slightly vary. The procedure up above was run on Android 11.
